version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.8.1
    - 1.9.0
    - 1.9.1
  - dependency-name: bootsnap
    versions:
    - 1.5.1
    - 1.6.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
    - 5.0.0
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: capybara
    versions:
    - 3.34.0
  - dependency-name: ffaker
    versions:
    - 2.17.0
