inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
